# Site settings
title: 'Terminal Root'
subtitle: 'Um pouco de muito sobre C++, Programação e Desenvolvimento Web.'
email: contato@terminalroot.com.br
author: 'Marcos Oliveira'
description: > # this means to ignore newlines until "baseurl:"
  Um pouco de muito sobre C++, Programação e Desenvolvimento de Games e Web.

twitter_username: TerminalRootTV
github_username:  Terroo
gitlab_username:  TerminalRoot
youtube_username:  TerminalRootTV
#
# Build settings
markdown: kramdown
highlighter: rouge
kramdown:
  input: GFM
  syntax_highlighter_opts:
    default_lang: html
#    css_class   : 'syntax'


permalink: /:year/:month/:title.html
#
# html minify
compress_html:
  clippings: all
  comments: all
  endings: []
  profile: false

# Links to include in menu navigation
# For external links add external: true
links:
  - title: Home
    url: /
  - title: Cursos
    url: /cursos
  - title: C++
    url: /cpp
  - title: Desenvolvimento de Games
    url: /games
  - title: OpenCV com C++
    url: /opencv
  - title: Lua - Linguagem de Programação
    url: /lua
