#!/bin/bash

# vim: noai:ts=4:sw=4:expandtab
#
# aptporn: Linux Mint, Ubuntu e Debian com i3 + Polybar + Rofi
# http://terminalroot.com.br/shell
#
# The MIT License (MIT)
#
# Copyright (c) 2018 Marcos Oliveira
#
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included in all
# copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
# SOFTWARE.

shopt -s extglob

usage() {
  cat <<EOF

usage: ${0##*/} [flags]

  Options:

    --install          No update system
    --install-all      Update all system
    --dep              Only install dependencies
    --version,-v       Show version
    --help,-h          Show this is message

* Marcos Oliveira - <terminalroot.com.br> - APTPORN 0.1

EOF
}


if [[ -z $1 || $1 = @(-h|--help) ]]; then
  usage
  exit $(( $# ? 0 : 1 ))
fi

version="${0##*/} version 0.1"

_start_all(){
    export _DIR="/tmp/polybar"
    export _SYMB=("----------------------")
    
    if [[ $(echo $LANG | cut -c 1-2) == "pt" ]] ; then
        export _MSGS=("Precisa instalar o" "É necessário estar logado no 'i3'" "INICIANDO A INSTALAÇÃO" "Abortando instalação." "Não rode com 'sudo' nem 'root'")    
    else
        export _MSGS=("You need to install" "You must be logged in to 'i3'" "STARTING THE INSTALLATION" "Aborting installation." "Do not run with 'sudo' or 'root'")
    fi
    
    [[ $(id -u) -eq 0 ]] && echo ${_MSGS[4]} && exit 0
}



_find_basics(){

    _basics=(i3 i3-wm i3status)
    _start=0
    _ini=0
     
    #while [[ "$_start" < "${#_basics[@]}" ]]; do
    #    ( ! which ${_basics[_start]} >&- 2>&-) && echo "${_MSGS[0]} '${_basics[_start]}'" && _ini=1                    
    #        let _start=_start+1
    #done
       
    if [[ "$DESKTOP_SESSION" != "i3" ]] ; then
        _ini=1
        echo ${_MSGS[1]}
    fi
    
    if [[ "$_ini" == 0 ]]; then
        echo ${_MSGS[2]}
        echo ${_SYMB[0]}
    else
        echo ${_MSGS[3]}
        exit 0
    fi
}

_get_updates(){
    sudo apt update && sudo apt upgrade -y && sudo apt dist-upgrade -y && sudo apt autoremove && sudo apt autoclean && sudo apt clean
}

_get_deps(){
    sudo apt install build-essential git cmake cmake-data pkg-config python3-sphinx libcairo2-dev libxcb1-dev libxcb-util0-dev libxcb-randr0-dev libxcb-composite0-dev python-xcbgen xcb-proto libxcb-image0-dev libxcb-ewmh-dev libxcb-icccm4-dev clang python2.7-dev libxcomposite-dev libxcursor-dev libxcb-xkb-dev libxcb-xrm-dev libxcb-cursor-dev libasound2-dev libpulse-dev i3-wm libjsoncpp-dev libmpdclient-dev libcurl4-openssl-dev libnl-genl-3-dev -y
}

_get_comps(){
    sudo apt install git fonts-font-awesome rofi feh vim neofetch imagemagick w3m -y
}

_set_polybar(){
    [[ -d "$_DIR" ]] && rm -rf "$_DIR"
    cd "/tmp"
    git clone --recursive https://github.com/polybar/polybar
    cd $_DIR && mkdir build && cd build
    cmake -DCMAKE_CXX_COMPILER="clang++" ..
    make -j$(nproc)
    sudo make install
    cd && rm -rf $_DIR
}

_set_confs(){
    [[ ! -d $HOME/.config/polybar ]] && mkdir -p $HOME/.config/polybar
    [[ ! -d $HOME/.local/share/fonts ]] && mkdir -p $HOME/.local/share/fonts
    [[ -d /tmp/fonts ]] && rm -rf /tmp/fonts
    git clone https://github.com/terroo/fonts /tmp/fonts
    mv /tmp/fonts/fonts/* $HOME/.local/share/fonts/
    fc-cache -fv
    mv /tmp/fonts/files/polybar/* $HOME/.config/polybar/
    chmod +x $HOME/.config/polybar/launch.sh
    [[ $(grep -i 'mint' /etc/issue) ]] && _d="Mint"
    [[ $(grep -i 'ubuntu' /etc/issue) ]] && _d="Ubuntu"
    [[ $(grep -i 'debian' /etc/issue) ]] && _d="Debian"
    sed -i "/$_d/s/^#//" $HOME/.config/polybar/scripts/menu
    chmod +x $HOME/.config/polybar/scripts/menu
    mv /tmp/fonts/files/i3/config $HOME/.config/i3/config
    mv /tmp/fonts/wallpapers/terminalroot-wall-35.jpg $HOME/.config/polybar/wallpaper.jpg
    feh --bg-scale $HOME/.config/polybar/wallpaper.jpg
    polybar topbar &
    i3-msg restart
    reset && clear && neofetch
}

aptporn(){
    _start_all
    _find_basics
    [[ "$1" -eq "1" ]] && _get_updates
    _get_deps
    _get_comps
    _set_polybar
    _set_confs
}

while [[ "$1" ]]; do
        case "$1" in
            "--install") aptporn "0" ;;
            "--install-all") aptporn "1" ;;
            "--dep") _get_deps ;;
            "--help"|"-h") usage ;;
            "--version"|"-v") printf "%s\n" "$version" ;;
            *) echo 'Invalid option.' && usage && exit 1 ;;
        esac
        shift
done

